spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum;
    username: sa
    password:
sql:
  init:
    mode: never
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  properties:
    hibernate:
      show_sql: true
      format_sql: true
#    defer-datasource-initialization: true
jwt:
  secret: secreto